### ISSUE TITLE
Can't get this working in Forge

### ISSUE THREAD

**Issue by gohan2091** [Index154/Random-ControlNet-Input#1]
Does this work with Forge? I cannot get it to work. I installed, restarted Forge and selected the script. I pasted the folder address where my PNGs are stored, I enable Control Net 0, I select Open Pose or Canny. When I click the generate button, nothing happens and I get this error: https://pastebin.com/i3KfYRHx

**Comment by beansfotos** [comment]
Ever found a fix for this? I still can't get it to work in FORGE

**Comment by gohan2091** [comment]
No fix, the creator would have to adapt it I would assume since the ControlNet on Forge is intergrated into the UI and not a separate extension. That would be my guess why it doesn't work. Should be an easy fix if someone knows what they are doing (which I don't :( )

**Comment by Index154** [comment]
Sorry, I never saw this issue until now because I didn't have notifications turned on.

I tried for a few hours to get it running with Forge but sadly I'm not up for the task. The builtin controlnet is missing a lot of functions compared to the official extension and I fear a lot of these would have to be added and tweaked manually to make this work the same way,

**Comment by gohan2091** [comment]
> Sorry, I never saw this issue until now because I didn't have notifications turned on.
> 
> I tried for a few hours to get it running with Forge but sadly I'm not up for the task. The builtin controlnet is missing a lot of functions compared to the official extension and I fear a lot of these would have to be added and tweaked manually to make this work the same way,

No problem. Well Forge is dead now. There is a fork called ReForge though but I've yet to try that (I've gone to A1111)
